### ISSUE TITLE
Does not work at all on Arch linux with sbcl

### ISSUE THREAD

**Issue by sirherrbatka** [orivej/pzmq#11]
Hi,

I was trying to use those bindings on arch linux with zeromq 4.1.4. I tried to use slightly altered code from unit test:

(defun request-response ()
    (pzmq:with-sockets ((sender :req) (receiver :rep))
      (pzmq:bind sender "inproc://source")
      (pzmq:connect receiver "inproc://source")
      (pzmq:send sender "test")
      (print (pzmq:recv-string receiver))))

However this code will trigger crash of whole lisp enviorment. SBCL will land in the ldb with message:

Argh! corrupted error depth, halting
fatal error encountered in SBCL pid 14032(tid 140737232664320):
%PRIMITIVE HALT called; the party is over.

I'm not sure what is going on here. Older zmq bindings seems to work correctly (though i can't seem to find how to recv with noblocking flag, other things are quite messy as well).

Do you have any clue on what is going on here?

**Comment by orivej** [comment]
It should have been fixed in this repository, but not in Quicklisp yet: https://github.com/orivej/pzmq/pull/10

**Comment by sirherrbatka** [comment]
https://github.com/freiksenet/cl-zmq here.

Thanks for answer.

**Comment by orivej** [comment]
Quicklisp dist has been updated.
