### ISSUE TITLE
ZMQ_ROUTER_HANDOVER is undefined

### ISSUE THREAD

**Issue by phoe** [orivej/pzmq#22]
https://github.com/zeromq/libzmq/blob/046ccfc408fd2f319a98fb89bb253274cc8b9cf3/include/zmq.h#L354

The new `socket-options` enum values in ZMQ are not reflected in PZMQ.

**Comment by orivej** [comment]
I'm going to add them in #23

**Comment by phoe** [comment]
Thanks!
